apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  labels:
    io.kompose.service: grafana-data
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi