apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    io.kompose.service: grafana

spec:
  replicas: 1

  selector:
    matchLabels:
      io.kompose.service: grafana

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        io.kompose.service: grafana

    spec:
      containers:
        - name: grafana

          image: grafana/grafana:latest

          ports:
            - containerPort: 3000
              protocol: TCP

          envFrom:
            - secretRef:
                name: mlops-secrets

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"

            limits:
              memory: "1Gi"
              cpu: "1000m"

          volumeMounts:

            # Persistencia de Grafana
            - name: grafana-storage
              mountPath: /var/lib/grafana

            # Dashboards provisionados
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
              readOnly: true

      volumes:

        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-data

        - name: grafana-dashboards
          configMap:
            name: grafana-cm2

      restartPolicy: Always