apiVersion: apps/v1
kind: Deployment

metadata:
  name: streamlit-ui

spec:
  replicas: 1

  selector:
    matchLabels:
      io.kompose.service: streamlit-ui

  revisionHistoryLimit: 2

  template:
    metadata:
      labels:
        io.kompose.service: streamlit-ui

    spec:
      containers:
        - name: streamlit-ui

          image: karabaharesu/mlops-final-streamlit-ui:26
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: mlops-config

            - secretRef:
                name: mlops-secrets

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"

            limits:
              memory: "256Mi"
              cpu: "250m"

          ports:
            - containerPort: 8501
              protocol: TCP

      restartPolicy: Always